# Generated by Django 2.2.3 on 2019-07-28 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20190728_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homograph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homographs', to='boards.Word')),
            ],
        ),
    ]
