# Generated by Django 2.2.3 on 2019-08-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_homograph'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='spell',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
